### ISSUE TITLE
Could not find module talib when run. 

### ISSUE THREAD

**Issue by manmastersg** [mikeozero/StockChart#2]
Hi 
Could not find module talib when run. 
How do you install talib module?

**Comment by manmastersg** [comment]
pip install TA_Lib‑0.4.24‑cp310‑cp310‑win_amd64.whl

**Comment by mikeozero** [comment]
It's a third-party package, you need to download and install it separately.
For Windows, try this (unofficial):  https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib
For Linux, try this: http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
