### ISSUE TITLE
Please advise how should the Table in stockchart database be created?

### ISSUE THREAD

**Issue by manmastersg** [mikeozero/StockChart#3]
Created the database stockchart in mysql however when run the app.py and click on the stockchart. It shows the follow error:

File "/home/rdp/python/StockChart/venv/lib/python3.12/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'stockchart.Stocks' doesn't exist")
[SQL: select distinct Ticker from Stocks order by Ticker]
(Background on this error at: https://sqlalche.me/e/20/f405)

===
Please advise how should the Table in stockchart database be created?

**Comment by mikeozero** [comment]
In this case, the database should has at least 6 tables: 'Stocks', 'Indices', 'MutualFunds', 'ETFs', 'Futures', and 'Currencies', and at least one column in each table: 'Ticker'.
If you bought data from third-party, you should just modify the codes in service.py according to your actual data structures. The columns in each table should be like: ['Ticker','Date','Open','Close','Low','High','Adj Close','Volume']
